services:
  db:
    image: postgres:16
    container_name: yelp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  jupyter:
    image: quay.io/jupyter/pyspark-notebook:python-3.11
    container_name: yelp-jupyter
    restart: unless-stopped
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      PYSPARK_PYTHON: python
      PYSPARK_DRIVER_PYTHON: python
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
      - ./jars:/home/jovyan/jars
    depends_on:
      db:
        condition: service_healthy
    command: start-notebook.sh --NotebookApp.token=${JUPYTER_TOKEN}

volumes:
  pgdata:
